
import csv
from datetime import datetime

def add_plant():
    """
    This function allow the user to add a new plant by adding the data related to it:
    plant_name: string value that indicates the name of the plant
     plant_type: string but the user have to enter the integer represent that string: 
     {1: "summer", 2: "spring",3: "winter",4: "autumn",5: "all"}
    location :plant location but the user have to enter the integer represent it: 
    {1:"outdoor", 2: "hall",3: "kitchen",4:"living room",5:"bedroom"}
    date_acquired:date time value in format : day-month-year (dd-mm-yyyy)
    watering_freq:integer that represent number of days between two watering events
    sunlight_req:a string indicating the amount of sun light the plant need but the user have to enter the integer represent that string:
    {1:"low",2:"medium",3:"high"}
    fertilizing_freq:integer that represent number of days between two fertilizing events
    repotting_freq:integer that represent number of days between two repotting events
    pruning_freq:integer that represent number of days between two pruning events
    plant_id: this will be auto generated by the function at the end based on the maximum id in the plants_data.csv file
    
    """

    
    plant_name=input("enter the plant name please")
    
    plant_types = {1: "summer", 2: "spring",3: "winter",4: "autumn",5: "all"}


    while True:
        try:
            plant_type_input=int (input("enter the plant type number as a number between 1-5 (summer=1, spring=2,winter=3,autumn=4,all-seasons=5)"))
            if plant_type_input in plant_types:
                plant_type=plant_types[plant_type_input]
                break
            else:
                print("error: you must choose a number between 1-5 based on your plant type")
        except ValueError:
             
            print("value error: you must enter a number between 1 -5 for plant type")
        
    plant_locations = {1:"outdoor", 2: "hall",3: "kitchen",4:"living room",5:"bedroom"}

    while True:
        try:
            plant_location_input=int (input("enter the plant location number as a number between 1-5 (outdoor=1, hall=2, kitchen=3, living room=4, bedroom=5)"))
            if plant_location_input in plant_locations:
                plant_location=plant_locations[plant_location_input]
                break
            else:
                print("error: you must choose a number between 1-5 based on your plant location")
        except ValueError:
          
            print("value error:you must enter a number between 1 - 5 for plant location")

    while True:
        try:
            date_aquired_input=input("enter the date you aquire the plant in format: day(DD)-month(MM)-year(YYYY)")
            date_input=datetime.strptime(date_aquired_input, "%d-%m-%Y")
            if date_input.date()> datetime.today().date():
                print("you cannot enter a day in future")
            else:
                plant_aquired_date= date_input.strftime("%d-%m-%Y")
                break
        except ValueError:
            print("Invalid date format. Please use DD-MM-YYYY.")

    sun_req_frequencies={1:"low",2:"medium",3:"high"}
    while True:
        try:
            plant_sun_req_input=int (input("enter the plant sun light need as number between 1-3:(low=1,medium=2,high=3)"))
            if plant_sun_req_input in sun_req_frequencies:
                plant_sun_requirement=sun_req_frequencies[plant_sun_req_input]
                break
            else:
                print("error: you must choose a number between 1-3 based on your plant need to sun light")
        except ValueError:
             
            print("value error: you must enter a number between 1 -3 for plant need of sun")

    while True:
        try:
            watering_frequency_input=int(input("enter the plant watering frequency in days between (1-35 days)"))
            if watering_frequency_input<1 or watering_frequency_input>35:
                print("the plant watering days frequency must be between 1 day and 35 days")
            else:
                watering_frequency=watering_frequency_input
                break
        except ValueError:
            print("value error: you must enter a number between 1 -35 for plant need of water")

    while True:
        try:
            fertilizing_frequency_input=int(input("enter the plant fertilizing frequency in days between (14-180 days)"))
            if fertilizing_frequency_input<14 or fertilizing_frequency_input>180:
                print("the plant fertilizing days frequency must be between 14 day and 180 days")
            else:
                fertilizing_frequency=fertilizing_frequency_input
                break
        except ValueError:
            print("value error: you must enter a number between 14 -180 for plant need of fertilizing")

    while True:
        try:
            repotting_frequency_input=int(input("enter the plant repotting frequency in days between (90-1095 days)"))
            if repotting_frequency_input<90 or repotting_frequency_input>1095:
                print("the plant repotting days frequency must be between 90 day and 1095 days")
            else:
                repotting_frequency = repotting_frequency_input
                break
        except ValueError:
            print("value error: you must enter a number between 90 -1095 for plant need of repotting")


    while True:
        try:
            pruning_frequency_input=int(input("enter the plant pruning frequency in days between (7-365 days)"))
            if pruning_frequency_input<7 or pruning_frequency_input>365:
                print("the plant pruning days frequency must be between 7 day and 365 days")
            else:
                pruning_frequency = pruning_frequency_input
                break
        except ValueError:
            print("value error: you must enter a number between 7 -365 for plant need of pruning")
    try:        
        with open('plants_data.csv', 'r',newline='') as file:
            content=csv.DictReader(file)
            max_id = 0
            for i in content:
                current_id = int(i["plant_id"])
                if current_id > max_id:
                    max_id = current_id
        new_id=max_id+1
    except FileNotFoundError:
        max_id = 0
    new_plant = {
    "plant_id": new_id,
    "plant_name":plant_name,
    "plant_type":plant_type,
    "location":plant_location,
    "date_acquired":plant_aquired_date,
    "watering_freq":watering_frequency,
    "sunlight_req":plant_sun_requirement,
    "fertilizing_freq":fertilizing_frequency,
    "repotting_freq":repotting_frequency,
    "pruning_freq":pruning_frequency
    }
    # to add a new entry to my data
    with open('plants_data.csv', mode='a', newline='') as file:
        fieldnames = [
        "plant_id", "plant_name", "plant_type", "location",
        "date_acquired", "watering_freq", "sunlight_req",
        "fertilizing_freq", "repotting_freq", "pruning_freq"]
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        if file.tell() == 0:   
            writer.writeheader()
        writer.writerow(new_plant)
        print(f"{plant_name} added successfully with ID {new_id}")

    

def activity_capture():

    """
    This function will allow selecting the plant by plant ID and then select the desired activity
    """

#Below will read the plant_id and plant_name from the plant_data file

    plants = []
    with open('plants_data.csv','r',newline = '') as file:
        content = csv.DictReader(file)
        print(f'\nPlant List:\n')
        for i in content:
            plants.append(i)
            print(f'{i['plant_id']} | {i['plant_name'].upper()}')
          
#Below will read user's input, where he/she will select a plant and the activity to be performed
    
    plant_id = input('\n**Enter plant ID from the above list: ')
    
    plant_name = ''
    
    for i in plants:
        if plant_id == i['plant_id']:
            plant_name = i['plant_name'].upper()
            break

#Below will check if the plant ID is valid
    
    if plant_name:
        print(f'\n**The selected plant is {plant_id} : {plant_name}')
    else:
        print('The entered plant ID is incorrect!')
        return
        
    activity = input('\n1.Watering. \n2.Fertilizing. \n3.Repotting. \n4.Pruning \n\n**Enter the number/s from the above activity separated by comma : ').split(",")
    
    plant_activity = {'date': datetime.now().strftime('%d-%m-%Y'),
                      'plant_id': plant_id,
                      'watered': False,
                      'fertilized': False,
                      'repotted': False,
                      'pruned': False}

#Below will check if the activity is valid

    for i in activity:      
        if i == '1':
            plant_activity['watered']= True
        elif i == '2':
            plant_activity['fertilized']= True
        elif i == '3':
            plant_activity['repotted']= True
        elif i == '4':
            plant_activity['pruned']= True  
        else:
            return f'Activity enter is incorrect!'

#Below will append the activity into the activity_log file   
    
    activity_log_headers = ['date','plant_id','watered','fertilized','repotted','pruned']  
    with open('activity_log.csv', 'a', newline='\n') as activity_log:
        plantlog_writer = csv.DictWriter(activity_log, fieldnames = activity_log_headers)
        if activity_log.tell() == 0:   
           plantlog_writer.writeheader()
        plantlog_writer.writerow(plant_activity)

    print(f'\n Activity log been saved')
    print(f'\n {plant_activity}')

def search_plants():
    """
    this function is designed to allow the user to search for plants based on their name or their locations and bring their data and care-needs
    the user can enter: 
    plant_search_method: this is a string represented by an integer 1 for name and 2 for location
    if the user choose 1: 
    plant_search_name: this will search for a match in the csv file for a plant with the same name case-insesetively
    if the user choose 2:
    plant_location: this is a string represented by an integer between 1 and 5 for locations:
    {1:"outdoor", 2: "hall",3: "kitchen",4:"living room",5:"bedroom"}


    """

    while True:
        try:
            plant_search_method_input=int (input("do you want to search plants using name or location? if you choose name enter(1), if you choose location enter(2)"))
            if plant_search_method_input==1 or plant_search_method_input==2:
                plant_search_method=plant_search_method_input
                break
            else:
                print("error: you must choose a number equals to 1 and 2 only based on your search type")
        except ValueError:
             
            print("value error: you must choose a number equals to 1 and 2 only based on your search type")

    if plant_search_method==1:
        plant_search_name=input("enter the plant name you need to search for it's details").strip().lower()
        found = False
        with open('plants_data.csv', 'r',newline='') as file:
            content=csv.DictReader(file)
            for i in content:
                if(i['plant_name'].lower()==plant_search_name):
                    print(f"""
                        Plant ID: {i['plant_id']}
                        Plant Type: {i['plant_type']}
                        Plant Name: {i['plant_name']}
                        Plant Location: {i['location']}
                        Plant Watering every {i['watering_freq']} days
                        Plant Sunlight need: {i['sunlight_req']}
                        Plant Repoting every {i['repotting_freq']} days
                        Plant Purning every {i['pruning_freq']} days
                        Plant Fertilizing every {i['fertilizing_freq']} days
                        """)
                    found=True
                    
              
                        
        if found==False:
            print(f"there is no plant with name: {plant_search_name} in the file")

    elif plant_search_method==2:
        plant_locations = {1:"outdoor", 2: "hall",3: "kitchen",4:"living room",5:"bedroom"}

        while True:
            try:
                plant_location_input=int (input("enter the plant location number as a number between 1-5 (outdoor=1, hall=2, kitchen=3, living room=4, bedroom=5)"))
                if plant_location_input in plant_locations:
                    plant_location=plant_locations[plant_location_input]
                    break
                else:
                    print("error: you must choose a number between 1-5 based on your plant location")
            except ValueError:
              
                print("value error:you must enter a number between 1 - 5 for plant location")
        found = False        
        with open('plants_data.csv', 'r',newline='') as file:
                content=csv.DictReader(file)
                for i in content:
                    if(i['location']==plant_location):
                        print(f"""
                        Plant ID: {i['plant_id']}
                        Plant Type: {i['plant_type']}
                        Plant Name: {i['plant_name']}
                        Plant Location: {i['location']}
                        Plant Watering every {i['watering_freq']} days
                        Plant Sunlight need: {i['sunlight_req']}
                        Plant Repoting every {i['repotting_freq']} days
                        Plant Purning every {i['pruning_freq']} days
                        Plant Fertilizing every {i['fertilizing_freq']} days
                        """)
                        found=True

                        
        if found==False:
            print(f"no plants found in location: {plant_location}")
    


def view_all_plants():
    """
    this function allow user just by selecting it to view all the plants he/she has
    """
    

    with open('plants_data.csv','r',newline = '') as file:
        content = csv.DictReader(file)
        print(f'\nPlant List:\n')
        for i in content:
          
            print(f"""
                        Plant ID: {i['plant_id']}
                        Plant Type: {i['plant_type']}
                        Plant Name: {i['plant_name']}
                        Plant Location: {i['location']}
                        Plant Watering every {i['watering_freq']} days
                        Plant Sunlight need: {i['sunlight_req']}
                        Plant Repoting every {i['repotting_freq']} days
                        Plant Purning every {i['pruning_freq']} days
                        Plant Fertilizing every {i['fertilizing_freq']} days
                        ------------------
                        """)
        

def add_photo():
    """
    this function allow the user to add an image with its path. 
    the user have to choose which plant he need to insert:
    plant_id: integer value represent the plant id 
    plant_path:the plant path with its image name
    then date_added: datetime value will be auto genrated which will be the date of today in format of day-month-year(dd-mm-yyyy)
    
    """
    
    while True:
        try:
            plant_id = int(input("Enter plant id: "))
        except:
            print("error: you need to enter a valid number")
            continue
            
        
        found = False
    
        with open('plants_data.csv', 'r', newline='') as file:
            content = csv.DictReader(file)
            for i in content:
                if i['plant_id'] == str(plant_id):
                    found = True
                    break
    
        if found:
            
            break   
        else:
            print("Invalid plant ID, please try again.")

    plant_path=input("please enter the image path and name:")
    date_added=datetime.today().strftime("%d-%m-%Y")
    new_photo = {
    "plant_id": plant_id,
    "photo_path":plant_path,
    "date_added":date_added
    }



    with open('plants_photos.csv', mode='a', newline='') as file:
        fieldnames = ["plant_id", "photo_path", "date_added"]
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        if file.tell() == 0:   
            writer.writeheader()
        writer.writerow(new_photo)
        print(f"photo added successfully with ID {plant_id}")



def plant_diag():

    diagnoses = {
        'yellow leaves': {
            'problem':'Overwatering',
            'treatment': 'Reduce watering, ensure pot has drainage holes, and let soil dry before watering again.'},
        'drooping leaves': {
            'problem': 'Underwatering',
            'treatment': 'Water the plant thoroughly and set a regular watering schedule.'},
        'brown tips': {
            'problem': 'Low humidity or over-fertilizing',
            'treatment': 'Increase humidity (mist leaves) and reduce fertilizer use.'},
        'wilting': {
            'problem': 'Root stress or improper watering',
            'treatment': 'Check soil moisture and adjust watering. Avoid overwatering.'},
        'slow growth': {
            'problem': 'Lack of nutrients or low light',
            'treatment': 'Move plant to brighter area and apply balanced fertilizer.'},
        'white spots': {
            'problem': 'Pests (fungus or insects)',
            'treatment': 'Clean leaves and use mild insecticidal soap or neem oil.'},
        'leaf curling': {
            'problem': 'Heat stress or underwatering',
            'treatment': 'Move plant away from heat source and adjust watering.'},
        'mold on soil': {
            'problem': 'Overwatering and poor airflow',
            'treatment': 'Let soil dry, improve ventilation, and remove top soil layer.'}
    }
    
    print('Select on of the below symptoms: ')
    print('1. Yellow Leaves')
    print('2. Drooping Leaves')
    print('3. Brown Tips')
    print('4. Wilting')
    print('5. Slow Growth')
    print('6. White Spots')
    print('7. Leaf Curling')
    print('8. Mold On Soil')
    user_input=input('\nEnter symptom number: ')

    if user_input == '1':
        diag = diagnoses['yellow leaves']
    elif user_input == '2':
        diag = diagnoses['drooping leaves']
    elif user_input == '3':
        diag = diagnoses['brown tips']
    elif user_input == '4':
        diag = diagnoses['wilting']
    elif user_input == '5':
        diag = diagnoses['slow growth']
    elif user_input == '6':
        diag = diagnoses['white spots']
    elif user_input == '7':
        diag = diagnoses['leaf curling']
    elif user_input == '8':
        diag = diagnoses['mold on soil']
    else:
        print('The entered symptom number is incorrect!')
        return

    print(f'Problem: {diag['problem']}')
    print(f'Treatment: {diag['treatment']}')




def plant_care():
    today = datetime.now()
#    id_by_user= int(input('Enter a plant_id from the list of plant_id above :'))	

    plant_freq = {}
   
#read csv files and list it for user to chose a plant
    try:
        with open('plants_data.csv', 'r',newline = '\n') as file: 
            reader = csv.DictReader(file)
            print('Available Plants:')
            
            for i in reader:
                print(f"{i['plant_id']},'-', {i['plant_name']}")
          
        # if it was string          
        id_by_user= input('Enter a plant_id from the list of plant_id above :').strip()
        
        
        with open('plants_data.csv', 'r',newline = '\n') as file: 
            reader = csv.DictReader(file)
            
            for i in reader:
                if i ['plant_id'] == id_by_user:
                    plant_freq = i
                    break
             
            if not plant_freq:
                print("Choose from the list of plant_id above:")
                return
             
    except ValueError:
            print("Invalid number. Choose from the list of plant_id above: ")
          
            return

   
    # to store latest date
    latest_date = {'watered': None, 'fertilized':None, 'repotted': None, 'pruned': None}
    task= ['watered', 'fertilized', 'repotted', 'pruned']
    
    try:
        with open('activity_log.csv', 'r',newline = '\n') as file: 
            reader = csv.DictReader(file)
        
            for a in reader:
                if a ['plant_id'] == id_by_user:
                # to get date format
                    l_date = datetime.strptime(a['date'], '%d-%m-%Y')
                    
                   #update latest_date 
                    for t in task:
                       if a [t].lower() == 'true':
                           if latest_date[t] is None or l_date > latest_date[t]:
                               latest_date[t] = l_date
                        
                        
    except ValueError:
        print("Error. CSV not found ")
        return                
             

     # (frequency column , record column, task)
    care_task = [('watering_freq', 'watered', 'watering'), ('fertilizing_freq', 'fertilized', 'fertilizing'), ('repotting_freq', 'repotted', 'repotting'), ('pruning_freq', 'pruned', 'pruning')]
    
    for freq_l, log_k, label in care_task:
        last_date = latest_date [log_k]
        freq = int (plant_freq[freq_l])
        
        # for first care for new plant
        if last_date is None:
            print (f'{label}: No logs. Plant needs care')
        else:
            days_count = (today - last_date).days
            if days_count >= freq:
                print(f'{label}: need care')
            else: 
                print(f"{label}: dosen't need care")
 
    

def main():
    print('1. Add a new plant to the collection.')
    print('2. Record a plant care activity.')
    print('3. View plants due for care.')
    print('4. Search plants by name or location.')
    print('5. View all plants.')
    print('6. Add photo for a plant.')
    print('7. ask the program for diagnosis and symptoms.')

    user_input = input(f'\nChoose one of the above actions: ')

    if user_input == '1':
        add_plant()
    elif user_input == '2':
        plant_care()
    elif user_input == '3':
        activity_capture()
    elif user_input == '4':
        search_plants()
    elif user_input == '5':
        view_all_plants()
    elif user_input == '6':
        add_photo()
    elif user_input == '7':
        plant_diag()
    else:
        return f'The entered option number is incorrect!'